language: node_js
dist: trusty
node_js:
  - "10"
sudo: required
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
  chrome: stable
before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - google-chrome-stable --no-sandbox
