language: node_js
os: osx
node_js:
  - "10"
cache: false
notifications:
  email:
    recipients:
      - discogs.enhancer@gmail.com
    on_success: never
    on_failure: always
script:
  - npm run build:dev
  - npm test
addons:
  chrome: stable
